### PR TITLE
Setup spec-prod

### LINKED ISSUE #134: Regenerate index.html
https://github.com/WICG/construct-stylesheets/pull/132 has not been deployed.

@tabatkins can you regenerate?

@saschanaz FYI

### PR DESCRIPTION
**Pull request by saschanaz**
This requires some prior steps before merging:

1. Renaming the current branch to `main` (rather than creating `main`, so that the existing PRs can be automatically redirected)
2. Create `gh-pages` again
3. Make sure the new `gh-pages` branch does not require approval for commits

Closes #134

### CODE REVIEW

**Comment by tabatkins** [comment]
Huh, it appears I do not have access to Settings on this repo. I'll figure out what's up with that.

**Comment by foolip** [comment]
@tabatkins any luck with getting access to the settings? I guess a WICG org admin like @cwilso can help?

**Comment by tabatkins** [comment]
No luck and I forgot about this, so thanks for the ping. Hopefully @cwilso or @yoavweiss can help.

**Comment by dontcallmedom** [comment]
I went through the steps highlighted above, now merging this

**Pull request merged**
